const leaderboardData = [
  {
    rank: 1,
    name: "Sherlock Holmes",
    title: "Master Detective",
    specialization: "Algorithm Expert",
    points: 4850,
    cases: 42,
    streak: 28,
    avatar: "🕵️",
  },
  {
    rank: 2,
    name: "T-800",
    title: "Chief Detective",
    specialization: "Data Structures",
    points: 4620,
    cases: 38,
    streak: 22,
    avatar: "🤖",
  },
  {
    rank: 3,
    name: "Merlin",
    title: "Chief Detective",
    specialization: "Logic Puzzles",
    points: 4390,
    cases: 35,
    streak: 18,
    avatar: "🧙",
  },
  {
    rank: 4,
    name: "Code Ninja",
    title: "Senior Detective",
    specialization: "String Manipulation",
    points: 4120,
    cases: 32,
    streak: 15,
    avatar: "🥷",
  },
  {
    rank: 5,
    name: "Debug Hunter",
    title: "Senior Detective",
    specialization: "Pattern Recognition",
    points: 3890,
    cases: 29,
    streak: 12,
    avatar: "🔍",
  },
  {
    rank: 6,
    name: "Pattern Master",
    title: "Detective",
    specialization: "Dynamic Programming",
    points: 3650,
    cases: 26,
    streak: 10,
    avatar: "🎯",
  },
];

export default leaderboardData;
